#!/bin/bash
#
# vihuela init script
# Tested on Redhat Linux 4.3
#
# uploadd-init.sh:       Starts Vihuela,  the Mariachi Upload Daemon
#
#
# chkconfig: 2345 90 10
# description: Starts and stops the upload daemon at boot time and shutdown. 
#
# processname: vihuela-bin.py
# hide: true

. /etc/init.d/functions

prog=vihuela-daemon.py
short=vihuela
fullprog=/usr/sbin/$prog

start() {
   echo -n $"Starting $short: "
   daemon $fullprog   
   ret=$?
   [ $ret -eq 0 ] && touch /var/lock/subsys/$prog
   echo
   return $ret
}

stop() {
   echo -n $"Shutting down $short: "
   mykillproc $prog -INT
   ret=$?
   [ $ret -eq 0 ] && rm -f /var/lock/subsys/$prog
   echo
   return $ret
}


reload() {
	stop
	start
}

restart() {
   echo $"Restarting $short:"
   stop
   start
}

# A function to stop a program.
# Custom version because of .py extension.
mykillproc() {
        RC=0
        notset=0

        # Save basename.
        base=$short

        # Find pid.
        pid=
        if [ -f /var/run/${base}.pid ]; then
                local line p
                read line < /var/run/${base}.pid
                for p in $line ; do
                        [ -z "${p//[0-9]/}" -a -d "/proc/$p" ] && pid="$pid $p"
                done
        fi
        if [ -z "$pid" ]; then
                pid=`pidof -o $$ -o $PPID -o %PPID -x $1 || \
                        pidof -o $$ -o $PPID -o %PPID -x $base`
        fi

        # Kill it.
        if [ -n "${pid:-}" ] ; then
                [ "$BOOTUP" = "verbose" -a -z "$LSB" ] && echo -n "$base "
                if [ "$notset" -eq "1" ] ; then
                       if checkpid $pid 2>&1; then
                           # TERM first, then KILL if not dead
                           kill -TERM $pid >/dev/null 2>&1
                           usleep 100000
                           if checkpid $pid && sleep 1 &&
                              checkpid $pid && sleep 3 &&
                              checkpid $pid ; then
                                kill -KILL $pid >/dev/null 2>&1
                                usleep 100000
                           fi
                        fi
                        checkpid $pid
                        RC=$?
                        [ "$RC" -eq 0 ] && failure $"$base shutdown" || success $"$base shutdown"
                        RC=$((! $RC))
                # use specified level only
                else
                        if checkpid $pid; then
                                kill $killlevel $pid >/dev/null 2>&1
                                RC=$?
                                [ "$RC" -eq 0 ] && success $"$base $killlevel" || failure $"$base $killlevel"
                        fi
                fi
        else
            failure $"$base shutdown"
            RC=1
        fi

        # Remove pid file if any.
        rm -f /var/run/$base.pid
        
        return $RC
}

mystatus() {
        local base=vihuela
        local cmdbase=vihuela-daemon.
        local pid

        # Next try "/var/run/*.pid" files
        if [ -f /var/run/${base}.pid ] ; then
                read pid < /var/run/${base}.pid
                if [ -n "$pid" ]; then
                	    commnd=`ps -p $pid -o comm=`
                        if [ "$commnd" = "$cmdbase" ]; then
                        	echo $"${base} (pid $pid) is running..."
 							return 0
                		else
                        	echo $"${base} dead but pid file exists"
                        	return 1
						fi
                fi
        fi
 
        # See if /var/lock/subsys/${base} exists
        if [ -f /var/lock/subsys/${base} ]; then
                echo $"${base} dead but subsys locked"
                return 2
        fi
        echo $"${base} is stopped"
        return 3
}


case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
    restart
    ;;
  reload)
        reload
        ;;
  condrestart)
        [ -f /var/lock/subsys/$prog ] && reload || :
        ;;
  status)
        mystatus 
        ;;
  *)
        echo $"Usage: vihuela {start|stop|status|restart|reload|condrestart}"
        exit 1
esac

exit $?
