#!/bin/bash
#
#
# cloudconfig       Perform various cloud-related configuration at init time.
#
# chkconfig: 2345 12 88
# description: Perform various cloud-releated configuration.
#
### BEGIN INIT INFO
# Provides: $network
### END INIT INFO

# Source function library.
. /etc/init.d/functions

# pull in sysconfig settings
[ -f /etc/sysconfig/cloudconfig.sysconfig ] && . /etc/sysconfig/cloudconfig.sysconfig

RETVAL=0

prog="cloudconfig"

start() {
    echo -n $"Starting cloudconfig: "
    for s in `ls /etc/cloudconfig/exec.d/*.sh` ; do 
    	$s
    done	
}

case "$1" in
start)
        start
        ;;
status)
        status_at
        ;;
*)
        echo $"Usage: $0 {start|status}"
        exit 1
esac

exit $?
exit $RETVAL
