/* srmH.h
   Generated by gSOAP 2.3.8 from srm.v1.1.h
   Copyright (C) 2001-2003 Genivia inc.
   All Rights Reserved.
*/
#ifndef srmH_H
#define srmH_H
#include "srmStub.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_BEGIN_NAMESPACE(srm)
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void * SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putattachments(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getattachments(struct soap*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (2)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_byte(struct soap*, char const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_tns__Integer
#define SOAP_TYPE_tns__Integer (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__Integer(struct soap*, int *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__Integer(struct soap*, int const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__Integer(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__Integer(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_tns__Integer(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_tns__Integer(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_xsd__int
#define SOAP_TYPE_xsd__int (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__int(struct soap*, int *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__int(struct soap*, int const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_xsd__int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_xsd__int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_int(struct soap*, int const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_tns__Long
#define SOAP_TYPE_tns__Long (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__Long(struct soap*, LONG64 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__Long(struct soap*, LONG64 const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__Long(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__Long(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_tns__Long(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_tns__Long(struct soap*, const char*, LONG64 *, const char*);

#ifndef SOAP_TYPE_xsd__long
#define SOAP_TYPE_xsd__long (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__long(struct soap*, LONG64 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__long(struct soap*, LONG64 const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__long(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__long(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_xsd__long(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_xsd__long(struct soap*, const char*, LONG64 *, const char*);

#ifndef SOAP_TYPE_LONG64
#define SOAP_TYPE_LONG64 (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_LONG64(struct soap*, LONG64 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_LONG64(struct soap*, LONG64 const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_LONG64(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_LONG64(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_LONG64(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_LONG64(struct soap*, const char*, LONG64 *, const char*);

#ifndef SOAP_TYPE_tns__Boolean
#define SOAP_TYPE_tns__Boolean (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__Boolean(struct soap*, enum _Enum1 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__Boolean(struct soap*, enum _Enum1 const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__Boolean(struct soap*, enum _Enum1 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__Boolean(struct soap*, const char*, int, const enum _Enum1 *, const char*);

SOAP_FMAC3 const char* SOAP_FMAC4 soap_tns__Boolean2s(struct soap*, enum _Enum1);
SOAP_FMAC3 enum _Enum1 * SOAP_FMAC4 soap_get_tns__Boolean(struct soap*, enum _Enum1 *, const char*, const char*);
SOAP_FMAC3 enum _Enum1 * SOAP_FMAC4 soap_in_tns__Boolean(struct soap*, const char*, enum _Enum1 *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_s2tns__Boolean(struct soap*, const char*, enum _Enum1 *);

#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__boolean(struct soap*, enum _Enum1 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__boolean(struct soap*, enum _Enum1 const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__boolean(struct soap*, enum _Enum1 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__boolean(struct soap*, const char*, int, const enum _Enum1 *, const char*);

SOAP_FMAC3 const char* SOAP_FMAC4 soap_xsd__boolean2s(struct soap*, enum _Enum1);
SOAP_FMAC3 enum _Enum1 * SOAP_FMAC4 soap_get_xsd__boolean(struct soap*, enum _Enum1 *, const char*, const char*);
SOAP_FMAC3 enum _Enum1 * SOAP_FMAC4 soap_in_xsd__boolean(struct soap*, const char*, enum _Enum1 *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_s2xsd__boolean(struct soap*, const char*, enum _Enum1 *);

#ifndef SOAP_TYPE__Enum1
#define SOAP_TYPE__Enum1 (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__Enum1(struct soap*, enum _Enum1 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__Enum1(struct soap*, enum _Enum1 const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__Enum1(struct soap*, enum _Enum1 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__Enum1(struct soap*, const char*, int, const enum _Enum1 *, const char*);

SOAP_FMAC3 const char* SOAP_FMAC4 soap__Enum12s(struct soap*, enum _Enum1);
SOAP_FMAC3 enum _Enum1 * SOAP_FMAC4 soap_get__Enum1(struct soap*, enum _Enum1 *, const char*, const char*);
SOAP_FMAC3 enum _Enum1 * SOAP_FMAC4 soap_in__Enum1(struct soap*, const char*, enum _Enum1 *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_s2_Enum1(struct soap*, const char*, enum _Enum1 *);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (94)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (93)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (91)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#endif

#ifndef SOAP_TYPE_tns__getFileMetaData
#define SOAP_TYPE_tns__getFileMetaData (88)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__getFileMetaData(struct soap*, struct tns__getFileMetaData const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__getFileMetaData(struct soap*, const struct tns__getFileMetaData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__getFileMetaData(struct soap*, struct tns__getFileMetaData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__getFileMetaData(struct soap*, struct tns__getFileMetaData *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__getFileMetaData(struct soap*, const char*, int, const struct tns__getFileMetaData *, const char*);
SOAP_FMAC3 struct tns__getFileMetaData * SOAP_FMAC4 soap_get_tns__getFileMetaData(struct soap*, struct tns__getFileMetaData *, const char*, const char*);
SOAP_FMAC3 struct tns__getFileMetaData * SOAP_FMAC4 soap_in_tns__getFileMetaData(struct soap*, const char*, struct tns__getFileMetaData *, const char*);

#ifndef SOAP_TYPE_tns__get
#define SOAP_TYPE_tns__get (85)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__get(struct soap*, struct tns__get const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__get(struct soap*, const struct tns__get *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__get(struct soap*, struct tns__get *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__get(struct soap*, struct tns__get *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__get(struct soap*, const char*, int, const struct tns__get *, const char*);
SOAP_FMAC3 struct tns__get * SOAP_FMAC4 soap_get_tns__get(struct soap*, struct tns__get *, const char*, const char*);
SOAP_FMAC3 struct tns__get * SOAP_FMAC4 soap_in_tns__get(struct soap*, const char*, struct tns__get *, const char*);

#ifndef SOAP_TYPE_tns__mkPermanent
#define SOAP_TYPE_tns__mkPermanent (82)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__mkPermanent(struct soap*, struct tns__mkPermanent const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__mkPermanent(struct soap*, const struct tns__mkPermanent *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__mkPermanent(struct soap*, struct tns__mkPermanent *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__mkPermanent(struct soap*, struct tns__mkPermanent *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__mkPermanent(struct soap*, const char*, int, const struct tns__mkPermanent *, const char*);
SOAP_FMAC3 struct tns__mkPermanent * SOAP_FMAC4 soap_get_tns__mkPermanent(struct soap*, struct tns__mkPermanent *, const char*, const char*);
SOAP_FMAC3 struct tns__mkPermanent * SOAP_FMAC4 soap_in_tns__mkPermanent(struct soap*, const char*, struct tns__mkPermanent *, const char*);

#ifndef SOAP_TYPE_tns__setFileStatus
#define SOAP_TYPE_tns__setFileStatus (79)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__setFileStatus(struct soap*, struct tns__setFileStatus const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__setFileStatus(struct soap*, const struct tns__setFileStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__setFileStatus(struct soap*, struct tns__setFileStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__setFileStatus(struct soap*, struct tns__setFileStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__setFileStatus(struct soap*, const char*, int, const struct tns__setFileStatus *, const char*);
SOAP_FMAC3 struct tns__setFileStatus * SOAP_FMAC4 soap_get_tns__setFileStatus(struct soap*, struct tns__setFileStatus *, const char*, const char*);
SOAP_FMAC3 struct tns__setFileStatus * SOAP_FMAC4 soap_in_tns__setFileStatus(struct soap*, const char*, struct tns__setFileStatus *, const char*);

#ifndef SOAP_TYPE_tns__unPin
#define SOAP_TYPE_tns__unPin (76)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__unPin(struct soap*, struct tns__unPin const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__unPin(struct soap*, const struct tns__unPin *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__unPin(struct soap*, struct tns__unPin *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__unPin(struct soap*, struct tns__unPin *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__unPin(struct soap*, const char*, int, const struct tns__unPin *, const char*);
SOAP_FMAC3 struct tns__unPin * SOAP_FMAC4 soap_get_tns__unPin(struct soap*, struct tns__unPin *, const char*, const char*);
SOAP_FMAC3 struct tns__unPin * SOAP_FMAC4 soap_in_tns__unPin(struct soap*, const char*, struct tns__unPin *, const char*);

#ifndef SOAP_TYPE_tns__pin
#define SOAP_TYPE_tns__pin (73)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__pin(struct soap*, struct tns__pin const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__pin(struct soap*, const struct tns__pin *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__pin(struct soap*, struct tns__pin *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__pin(struct soap*, struct tns__pin *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__pin(struct soap*, const char*, int, const struct tns__pin *, const char*);
SOAP_FMAC3 struct tns__pin * SOAP_FMAC4 soap_get_tns__pin(struct soap*, struct tns__pin *, const char*, const char*);
SOAP_FMAC3 struct tns__pin * SOAP_FMAC4 soap_in_tns__pin(struct soap*, const char*, struct tns__pin *, const char*);

#ifndef SOAP_TYPE_tns__advisoryDelete
#define SOAP_TYPE_tns__advisoryDelete (70)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__advisoryDelete(struct soap*, struct tns__advisoryDelete const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__advisoryDelete(struct soap*, const struct tns__advisoryDelete *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__advisoryDelete(struct soap*, struct tns__advisoryDelete *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__advisoryDelete(struct soap*, struct tns__advisoryDelete *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__advisoryDelete(struct soap*, const char*, int, const struct tns__advisoryDelete *, const char*);
SOAP_FMAC3 struct tns__advisoryDelete * SOAP_FMAC4 soap_get_tns__advisoryDelete(struct soap*, struct tns__advisoryDelete *, const char*, const char*);
SOAP_FMAC3 struct tns__advisoryDelete * SOAP_FMAC4 soap_in_tns__advisoryDelete(struct soap*, const char*, struct tns__advisoryDelete *, const char*);

#ifndef SOAP_TYPE_tns__getEstGetTime
#define SOAP_TYPE_tns__getEstGetTime (67)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__getEstGetTime(struct soap*, struct tns__getEstGetTime const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__getEstGetTime(struct soap*, const struct tns__getEstGetTime *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__getEstGetTime(struct soap*, struct tns__getEstGetTime *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__getEstGetTime(struct soap*, struct tns__getEstGetTime *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__getEstGetTime(struct soap*, const char*, int, const struct tns__getEstGetTime *, const char*);
SOAP_FMAC3 struct tns__getEstGetTime * SOAP_FMAC4 soap_get_tns__getEstGetTime(struct soap*, struct tns__getEstGetTime *, const char*, const char*);
SOAP_FMAC3 struct tns__getEstGetTime * SOAP_FMAC4 soap_in_tns__getEstGetTime(struct soap*, const char*, struct tns__getEstGetTime *, const char*);

#ifndef SOAP_TYPE_tns__getProtocols
#define SOAP_TYPE_tns__getProtocols (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__getProtocols(struct soap*, struct tns__getProtocols const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__getProtocols(struct soap*, const struct tns__getProtocols *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__getProtocols(struct soap*, struct tns__getProtocols *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__getProtocols(struct soap*, struct tns__getProtocols *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__getProtocols(struct soap*, const char*, int, const struct tns__getProtocols *, const char*);
SOAP_FMAC3 struct tns__getProtocols * SOAP_FMAC4 soap_get_tns__getProtocols(struct soap*, struct tns__getProtocols *, const char*, const char*);
SOAP_FMAC3 struct tns__getProtocols * SOAP_FMAC4 soap_in_tns__getProtocols(struct soap*, const char*, struct tns__getProtocols *, const char*);

#ifndef SOAP_TYPE_tns__copy
#define SOAP_TYPE_tns__copy (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__copy(struct soap*, struct tns__copy const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__copy(struct soap*, const struct tns__copy *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__copy(struct soap*, struct tns__copy *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__copy(struct soap*, struct tns__copy *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__copy(struct soap*, const char*, int, const struct tns__copy *, const char*);
SOAP_FMAC3 struct tns__copy * SOAP_FMAC4 soap_get_tns__copy(struct soap*, struct tns__copy *, const char*, const char*);
SOAP_FMAC3 struct tns__copy * SOAP_FMAC4 soap_in_tns__copy(struct soap*, const char*, struct tns__copy *, const char*);

#ifndef SOAP_TYPE_tns__getRequestStatus
#define SOAP_TYPE_tns__getRequestStatus (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__getRequestStatus(struct soap*, struct tns__getRequestStatus const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__getRequestStatus(struct soap*, const struct tns__getRequestStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__getRequestStatus(struct soap*, struct tns__getRequestStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__getRequestStatus(struct soap*, struct tns__getRequestStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__getRequestStatus(struct soap*, const char*, int, const struct tns__getRequestStatus *, const char*);
SOAP_FMAC3 struct tns__getRequestStatus * SOAP_FMAC4 soap_get_tns__getRequestStatus(struct soap*, struct tns__getRequestStatus *, const char*, const char*);
SOAP_FMAC3 struct tns__getRequestStatus * SOAP_FMAC4 soap_in_tns__getRequestStatus(struct soap*, const char*, struct tns__getRequestStatus *, const char*);

#ifndef SOAP_TYPE_tns__put
#define SOAP_TYPE_tns__put (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__put(struct soap*, struct tns__put const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__put(struct soap*, const struct tns__put *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__put(struct soap*, struct tns__put *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__put(struct soap*, struct tns__put *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__put(struct soap*, const char*, int, const struct tns__put *, const char*);
SOAP_FMAC3 struct tns__put * SOAP_FMAC4 soap_get_tns__put(struct soap*, struct tns__put *, const char*, const char*);
SOAP_FMAC3 struct tns__put * SOAP_FMAC4 soap_in_tns__put(struct soap*, const char*, struct tns__put *, const char*);

#ifndef SOAP_TYPE_tns__getEstPutTime
#define SOAP_TYPE_tns__getEstPutTime (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__getEstPutTime(struct soap*, struct tns__getEstPutTime const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__getEstPutTime(struct soap*, const struct tns__getEstPutTime *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__getEstPutTime(struct soap*, struct tns__getEstPutTime *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__getEstPutTime(struct soap*, struct tns__getEstPutTime *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__getEstPutTime(struct soap*, const char*, int, const struct tns__getEstPutTime *, const char*);
SOAP_FMAC3 struct tns__getEstPutTime * SOAP_FMAC4 soap_get_tns__getEstPutTime(struct soap*, struct tns__getEstPutTime *, const char*, const char*);
SOAP_FMAC3 struct tns__getEstPutTime * SOAP_FMAC4 soap_in_tns__getEstPutTime(struct soap*, const char*, struct tns__getEstPutTime *, const char*);

#ifndef SOAP_TYPE_tns__ping
#define SOAP_TYPE_tns__ping (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__ping(struct soap*, struct tns__ping const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__ping(struct soap*, const struct tns__ping *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__ping(struct soap*, struct tns__ping *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__ping(struct soap*, struct tns__ping *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__ping(struct soap*, const char*, int, const struct tns__ping *, const char*);
SOAP_FMAC3 struct tns__ping * SOAP_FMAC4 soap_get_tns__ping(struct soap*, struct tns__ping *, const char*, const char*);
SOAP_FMAC3 struct tns__ping * SOAP_FMAC4 soap_in_tns__ping(struct soap*, const char*, struct tns__ping *, const char*);

#ifndef SOAP_TYPE_ArrayOfboolean
#define SOAP_TYPE_ArrayOfboolean (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ArrayOfboolean(struct soap*, struct ArrayOfboolean const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_ArrayOfboolean(struct soap*, struct ArrayOfboolean const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ArrayOfboolean(struct soap*, struct ArrayOfboolean *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ArrayOfboolean(struct soap*, struct ArrayOfboolean *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOfboolean(struct soap*, const char*, int, const struct ArrayOfboolean *, const char*);
SOAP_FMAC3 struct ArrayOfboolean * SOAP_FMAC4 soap_get_ArrayOfboolean(struct soap*, struct ArrayOfboolean *, const char*, const char*);
SOAP_FMAC3 struct ArrayOfboolean * SOAP_FMAC4 soap_in_ArrayOfboolean(struct soap*, const char*, struct ArrayOfboolean *, const char*);

#ifndef SOAP_TYPE_tns__unPinResponse
#define SOAP_TYPE_tns__unPinResponse (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__unPinResponse(struct soap*, struct tns__unPinResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__unPinResponse(struct soap*, const struct tns__unPinResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__unPinResponse(struct soap*, struct tns__unPinResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__unPinResponse(struct soap*, struct tns__unPinResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__unPinResponse(struct soap*, const char*, int, const struct tns__unPinResponse *, const char*);
SOAP_FMAC3 struct tns__unPinResponse * SOAP_FMAC4 soap_get_tns__unPinResponse(struct soap*, struct tns__unPinResponse *, const char*, const char*);
SOAP_FMAC3 struct tns__unPinResponse * SOAP_FMAC4 soap_in_tns__unPinResponse(struct soap*, const char*, struct tns__unPinResponse *, const char*);

#ifndef SOAP_TYPE_tns__setFileStatusResponse
#define SOAP_TYPE_tns__setFileStatusResponse (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__setFileStatusResponse(struct soap*, struct tns__setFileStatusResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__setFileStatusResponse(struct soap*, const struct tns__setFileStatusResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__setFileStatusResponse(struct soap*, struct tns__setFileStatusResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__setFileStatusResponse(struct soap*, struct tns__setFileStatusResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__setFileStatusResponse(struct soap*, const char*, int, const struct tns__setFileStatusResponse *, const char*);
SOAP_FMAC3 struct tns__setFileStatusResponse * SOAP_FMAC4 soap_get_tns__setFileStatusResponse(struct soap*, struct tns__setFileStatusResponse *, const char*, const char*);
SOAP_FMAC3 struct tns__setFileStatusResponse * SOAP_FMAC4 soap_in_tns__setFileStatusResponse(struct soap*, const char*, struct tns__setFileStatusResponse *, const char*);

#ifndef SOAP_TYPE_tns__getProtocolsResponse
#define SOAP_TYPE_tns__getProtocolsResponse (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__getProtocolsResponse(struct soap*, struct tns__getProtocolsResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__getProtocolsResponse(struct soap*, const struct tns__getProtocolsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__getProtocolsResponse(struct soap*, struct tns__getProtocolsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__getProtocolsResponse(struct soap*, struct tns__getProtocolsResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__getProtocolsResponse(struct soap*, const char*, int, const struct tns__getProtocolsResponse *, const char*);
SOAP_FMAC3 struct tns__getProtocolsResponse * SOAP_FMAC4 soap_get_tns__getProtocolsResponse(struct soap*, struct tns__getProtocolsResponse *, const char*, const char*);
SOAP_FMAC3 struct tns__getProtocolsResponse * SOAP_FMAC4 soap_in_tns__getProtocolsResponse(struct soap*, const char*, struct tns__getProtocolsResponse *, const char*);

#ifndef SOAP_TYPE_tns__getRequestStatusResponse
#define SOAP_TYPE_tns__getRequestStatusResponse (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__getRequestStatusResponse(struct soap*, struct tns__getRequestStatusResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__getRequestStatusResponse(struct soap*, const struct tns__getRequestStatusResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__getRequestStatusResponse(struct soap*, struct tns__getRequestStatusResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__getRequestStatusResponse(struct soap*, struct tns__getRequestStatusResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__getRequestStatusResponse(struct soap*, const char*, int, const struct tns__getRequestStatusResponse *, const char*);
SOAP_FMAC3 struct tns__getRequestStatusResponse * SOAP_FMAC4 soap_get_tns__getRequestStatusResponse(struct soap*, struct tns__getRequestStatusResponse *, const char*, const char*);
SOAP_FMAC3 struct tns__getRequestStatusResponse * SOAP_FMAC4 soap_in_tns__getRequestStatusResponse(struct soap*, const char*, struct tns__getRequestStatusResponse *, const char*);

#ifndef SOAP_TYPE_tns__getFileMetaDataResponse
#define SOAP_TYPE_tns__getFileMetaDataResponse (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__getFileMetaDataResponse(struct soap*, struct tns__getFileMetaDataResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__getFileMetaDataResponse(struct soap*, const struct tns__getFileMetaDataResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__getFileMetaDataResponse(struct soap*, struct tns__getFileMetaDataResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__getFileMetaDataResponse(struct soap*, struct tns__getFileMetaDataResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__getFileMetaDataResponse(struct soap*, const char*, int, const struct tns__getFileMetaDataResponse *, const char*);
SOAP_FMAC3 struct tns__getFileMetaDataResponse * SOAP_FMAC4 soap_get_tns__getFileMetaDataResponse(struct soap*, struct tns__getFileMetaDataResponse *, const char*, const char*);
SOAP_FMAC3 struct tns__getFileMetaDataResponse * SOAP_FMAC4 soap_in_tns__getFileMetaDataResponse(struct soap*, const char*, struct tns__getFileMetaDataResponse *, const char*);

#ifndef SOAP_TYPE_tns__pingResponse
#define SOAP_TYPE_tns__pingResponse (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__pingResponse(struct soap*, struct tns__pingResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__pingResponse(struct soap*, const struct tns__pingResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__pingResponse(struct soap*, struct tns__pingResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__pingResponse(struct soap*, struct tns__pingResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__pingResponse(struct soap*, const char*, int, const struct tns__pingResponse *, const char*);
SOAP_FMAC3 struct tns__pingResponse * SOAP_FMAC4 soap_get_tns__pingResponse(struct soap*, struct tns__pingResponse *, const char*, const char*);
SOAP_FMAC3 struct tns__pingResponse * SOAP_FMAC4 soap_in_tns__pingResponse(struct soap*, const char*, struct tns__pingResponse *, const char*);

#ifndef SOAP_TYPE_tns__pinResponse
#define SOAP_TYPE_tns__pinResponse (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__pinResponse(struct soap*, struct tns__pinResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__pinResponse(struct soap*, const struct tns__pinResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__pinResponse(struct soap*, struct tns__pinResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__pinResponse(struct soap*, struct tns__pinResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__pinResponse(struct soap*, const char*, int, const struct tns__pinResponse *, const char*);
SOAP_FMAC3 struct tns__pinResponse * SOAP_FMAC4 soap_get_tns__pinResponse(struct soap*, struct tns__pinResponse *, const char*, const char*);
SOAP_FMAC3 struct tns__pinResponse * SOAP_FMAC4 soap_in_tns__pinResponse(struct soap*, const char*, struct tns__pinResponse *, const char*);

#ifndef SOAP_TYPE_tns__getEstPutTimeResponse
#define SOAP_TYPE_tns__getEstPutTimeResponse (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__getEstPutTimeResponse(struct soap*, struct tns__getEstPutTimeResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__getEstPutTimeResponse(struct soap*, const struct tns__getEstPutTimeResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__getEstPutTimeResponse(struct soap*, struct tns__getEstPutTimeResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__getEstPutTimeResponse(struct soap*, struct tns__getEstPutTimeResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__getEstPutTimeResponse(struct soap*, const char*, int, const struct tns__getEstPutTimeResponse *, const char*);
SOAP_FMAC3 struct tns__getEstPutTimeResponse * SOAP_FMAC4 soap_get_tns__getEstPutTimeResponse(struct soap*, struct tns__getEstPutTimeResponse *, const char*, const char*);
SOAP_FMAC3 struct tns__getEstPutTimeResponse * SOAP_FMAC4 soap_in_tns__getEstPutTimeResponse(struct soap*, const char*, struct tns__getEstPutTimeResponse *, const char*);

#ifndef SOAP_TYPE_tns__getEstGetTimeResponse
#define SOAP_TYPE_tns__getEstGetTimeResponse (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__getEstGetTimeResponse(struct soap*, struct tns__getEstGetTimeResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__getEstGetTimeResponse(struct soap*, const struct tns__getEstGetTimeResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__getEstGetTimeResponse(struct soap*, struct tns__getEstGetTimeResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__getEstGetTimeResponse(struct soap*, struct tns__getEstGetTimeResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__getEstGetTimeResponse(struct soap*, const char*, int, const struct tns__getEstGetTimeResponse *, const char*);
SOAP_FMAC3 struct tns__getEstGetTimeResponse * SOAP_FMAC4 soap_get_tns__getEstGetTimeResponse(struct soap*, struct tns__getEstGetTimeResponse *, const char*, const char*);
SOAP_FMAC3 struct tns__getEstGetTimeResponse * SOAP_FMAC4 soap_in_tns__getEstGetTimeResponse(struct soap*, const char*, struct tns__getEstGetTimeResponse *, const char*);

#ifndef SOAP_TYPE_tns__copyResponse
#define SOAP_TYPE_tns__copyResponse (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__copyResponse(struct soap*, struct tns__copyResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__copyResponse(struct soap*, const struct tns__copyResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__copyResponse(struct soap*, struct tns__copyResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__copyResponse(struct soap*, struct tns__copyResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__copyResponse(struct soap*, const char*, int, const struct tns__copyResponse *, const char*);
SOAP_FMAC3 struct tns__copyResponse * SOAP_FMAC4 soap_get_tns__copyResponse(struct soap*, struct tns__copyResponse *, const char*, const char*);
SOAP_FMAC3 struct tns__copyResponse * SOAP_FMAC4 soap_in_tns__copyResponse(struct soap*, const char*, struct tns__copyResponse *, const char*);

#ifndef SOAP_TYPE_tns__mkPermanentResponse
#define SOAP_TYPE_tns__mkPermanentResponse (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__mkPermanentResponse(struct soap*, struct tns__mkPermanentResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__mkPermanentResponse(struct soap*, const struct tns__mkPermanentResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__mkPermanentResponse(struct soap*, struct tns__mkPermanentResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__mkPermanentResponse(struct soap*, struct tns__mkPermanentResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__mkPermanentResponse(struct soap*, const char*, int, const struct tns__mkPermanentResponse *, const char*);
SOAP_FMAC3 struct tns__mkPermanentResponse * SOAP_FMAC4 soap_get_tns__mkPermanentResponse(struct soap*, struct tns__mkPermanentResponse *, const char*, const char*);
SOAP_FMAC3 struct tns__mkPermanentResponse * SOAP_FMAC4 soap_in_tns__mkPermanentResponse(struct soap*, const char*, struct tns__mkPermanentResponse *, const char*);

#ifndef SOAP_TYPE_ns11__RequestFileStatus
#define SOAP_TYPE_ns11__RequestFileStatus (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns11__RequestFileStatus(struct soap*, struct ns11__RequestFileStatus const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_ns11__RequestFileStatus(struct soap*, const struct ns11__RequestFileStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns11__RequestFileStatus(struct soap*, struct ns11__RequestFileStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns11__RequestFileStatus(struct soap*, struct ns11__RequestFileStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns11__RequestFileStatus(struct soap*, const char*, int, const struct ns11__RequestFileStatus *, const char*);
SOAP_FMAC3 struct ns11__RequestFileStatus * SOAP_FMAC4 soap_get_ns11__RequestFileStatus(struct soap*, struct ns11__RequestFileStatus *, const char*, const char*);
SOAP_FMAC3 struct ns11__RequestFileStatus * SOAP_FMAC4 soap_in_ns11__RequestFileStatus(struct soap*, const char*, struct ns11__RequestFileStatus *, const char*);

#ifndef SOAP_TYPE_tns__putResponse
#define SOAP_TYPE_tns__putResponse (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__putResponse(struct soap*, struct tns__putResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__putResponse(struct soap*, const struct tns__putResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__putResponse(struct soap*, struct tns__putResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__putResponse(struct soap*, struct tns__putResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__putResponse(struct soap*, const char*, int, const struct tns__putResponse *, const char*);
SOAP_FMAC3 struct tns__putResponse * SOAP_FMAC4 soap_get_tns__putResponse(struct soap*, struct tns__putResponse *, const char*, const char*);
SOAP_FMAC3 struct tns__putResponse * SOAP_FMAC4 soap_in_tns__putResponse(struct soap*, const char*, struct tns__putResponse *, const char*);

#ifndef SOAP_TYPE_ArrayOflong
#define SOAP_TYPE_ArrayOflong (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ArrayOflong(struct soap*, struct ArrayOflong const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_ArrayOflong(struct soap*, struct ArrayOflong const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ArrayOflong(struct soap*, struct ArrayOflong *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ArrayOflong(struct soap*, struct ArrayOflong *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOflong(struct soap*, const char*, int, const struct ArrayOflong *, const char*);
SOAP_FMAC3 struct ArrayOflong * SOAP_FMAC4 soap_get_ArrayOflong(struct soap*, struct ArrayOflong *, const char*, const char*);
SOAP_FMAC3 struct ArrayOflong * SOAP_FMAC4 soap_in_ArrayOflong(struct soap*, const char*, struct ArrayOflong *, const char*);

#ifndef SOAP_TYPE_ArrayOfstring
#define SOAP_TYPE_ArrayOfstring (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ArrayOfstring(struct soap*, struct ArrayOfstring const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_ArrayOfstring(struct soap*, struct ArrayOfstring const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ArrayOfstring(struct soap*, struct ArrayOfstring *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ArrayOfstring(struct soap*, struct ArrayOfstring *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOfstring(struct soap*, const char*, int, const struct ArrayOfstring *, const char*);
SOAP_FMAC3 struct ArrayOfstring * SOAP_FMAC4 soap_get_ArrayOfstring(struct soap*, struct ArrayOfstring *, const char*, const char*);
SOAP_FMAC3 struct ArrayOfstring * SOAP_FMAC4 soap_in_ArrayOfstring(struct soap*, const char*, struct ArrayOfstring *, const char*);

#ifndef SOAP_TYPE_ns11__FileMetaData
#define SOAP_TYPE_ns11__FileMetaData (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns11__FileMetaData(struct soap*, struct ns11__FileMetaData const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_ns11__FileMetaData(struct soap*, const struct ns11__FileMetaData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns11__FileMetaData(struct soap*, struct ns11__FileMetaData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns11__FileMetaData(struct soap*, struct ns11__FileMetaData *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns11__FileMetaData(struct soap*, const char*, int, const struct ns11__FileMetaData *, const char*);
SOAP_FMAC3 struct ns11__FileMetaData * SOAP_FMAC4 soap_get_ns11__FileMetaData(struct soap*, struct ns11__FileMetaData *, const char*, const char*);
SOAP_FMAC3 struct ns11__FileMetaData * SOAP_FMAC4 soap_in_ns11__FileMetaData(struct soap*, const char*, struct ns11__FileMetaData *, const char*);

#ifndef SOAP_TYPE_ArrayOfFileMetaData
#define SOAP_TYPE_ArrayOfFileMetaData (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ArrayOfFileMetaData(struct soap*, struct ArrayOfFileMetaData const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_ArrayOfFileMetaData(struct soap*, struct ArrayOfFileMetaData const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ArrayOfFileMetaData(struct soap*, struct ArrayOfFileMetaData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ArrayOfFileMetaData(struct soap*, struct ArrayOfFileMetaData *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOfFileMetaData(struct soap*, const char*, int, const struct ArrayOfFileMetaData *, const char*);
SOAP_FMAC3 struct ArrayOfFileMetaData * SOAP_FMAC4 soap_get_ArrayOfFileMetaData(struct soap*, struct ArrayOfFileMetaData *, const char*, const char*);
SOAP_FMAC3 struct ArrayOfFileMetaData * SOAP_FMAC4 soap_in_ArrayOfFileMetaData(struct soap*, const char*, struct ArrayOfFileMetaData *, const char*);

#ifndef SOAP_TYPE_ArrayOfRequestFileStatus
#define SOAP_TYPE_ArrayOfRequestFileStatus (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ArrayOfRequestFileStatus(struct soap*, struct ArrayOfRequestFileStatus const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_ArrayOfRequestFileStatus(struct soap*, struct ArrayOfRequestFileStatus const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ArrayOfRequestFileStatus(struct soap*, struct ArrayOfRequestFileStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ArrayOfRequestFileStatus(struct soap*, struct ArrayOfRequestFileStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOfRequestFileStatus(struct soap*, const char*, int, const struct ArrayOfRequestFileStatus *, const char*);
SOAP_FMAC3 struct ArrayOfRequestFileStatus * SOAP_FMAC4 soap_get_ArrayOfRequestFileStatus(struct soap*, struct ArrayOfRequestFileStatus *, const char*, const char*);
SOAP_FMAC3 struct ArrayOfRequestFileStatus * SOAP_FMAC4 soap_in_ArrayOfRequestFileStatus(struct soap*, const char*, struct ArrayOfRequestFileStatus *, const char*);

#ifndef SOAP_TYPE_tns__advisoryDeleteResponse
#define SOAP_TYPE_tns__advisoryDeleteResponse (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__advisoryDeleteResponse(struct soap*, struct tns__advisoryDeleteResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__advisoryDeleteResponse(struct soap*, const struct tns__advisoryDeleteResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__advisoryDeleteResponse(struct soap*, struct tns__advisoryDeleteResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__advisoryDeleteResponse(struct soap*, struct tns__advisoryDeleteResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__advisoryDeleteResponse(struct soap*, const char*, int, const struct tns__advisoryDeleteResponse *, const char*);
SOAP_FMAC3 struct tns__advisoryDeleteResponse * SOAP_FMAC4 soap_get_tns__advisoryDeleteResponse(struct soap*, struct tns__advisoryDeleteResponse *, const char*, const char*);
SOAP_FMAC3 struct tns__advisoryDeleteResponse * SOAP_FMAC4 soap_in_tns__advisoryDeleteResponse(struct soap*, const char*, struct tns__advisoryDeleteResponse *, const char*);

#ifndef SOAP_TYPE_ns11__RequestStatus
#define SOAP_TYPE_ns11__RequestStatus (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns11__RequestStatus(struct soap*, struct ns11__RequestStatus const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_ns11__RequestStatus(struct soap*, const struct ns11__RequestStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns11__RequestStatus(struct soap*, struct ns11__RequestStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns11__RequestStatus(struct soap*, struct ns11__RequestStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns11__RequestStatus(struct soap*, const char*, int, const struct ns11__RequestStatus *, const char*);
SOAP_FMAC3 struct ns11__RequestStatus * SOAP_FMAC4 soap_get_ns11__RequestStatus(struct soap*, struct ns11__RequestStatus *, const char*, const char*);
SOAP_FMAC3 struct ns11__RequestStatus * SOAP_FMAC4 soap_in_ns11__RequestStatus(struct soap*, const char*, struct ns11__RequestStatus *, const char*);

#ifndef SOAP_TYPE_tns__getResponse
#define SOAP_TYPE_tns__getResponse (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__getResponse(struct soap*, struct tns__getResponse const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_tns__getResponse(struct soap*, const struct tns__getResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__getResponse(struct soap*, struct tns__getResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__getResponse(struct soap*, struct tns__getResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__getResponse(struct soap*, const char*, int, const struct tns__getResponse *, const char*);
SOAP_FMAC3 struct tns__getResponse * SOAP_FMAC4 soap_get_tns__getResponse(struct soap*, struct tns__getResponse *, const char*, const char*);
SOAP_FMAC3 struct tns__getResponse * SOAP_FMAC4 soap_in_tns__getResponse(struct soap*, const char*, struct tns__getResponse *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (95)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (92)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_PointerTotns__getFileMetaDataResponse
#define SOAP_TYPE_PointerTotns__getFileMetaDataResponse (86)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__getFileMetaDataResponse(struct soap*, struct tns__getFileMetaDataResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotns__getFileMetaDataResponse(struct soap*, struct tns__getFileMetaDataResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotns__getFileMetaDataResponse(struct soap*, struct tns__getFileMetaDataResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__getFileMetaDataResponse(struct soap*, struct tns__getFileMetaDataResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__getFileMetaDataResponse(struct soap*, const char *, int, struct tns__getFileMetaDataResponse *const*, const char *);
SOAP_FMAC3 struct tns__getFileMetaDataResponse ** SOAP_FMAC4 soap_get_PointerTotns__getFileMetaDataResponse(struct soap*, struct tns__getFileMetaDataResponse **, const char*, const char*);
SOAP_FMAC3 struct tns__getFileMetaDataResponse ** SOAP_FMAC4 soap_in_PointerTotns__getFileMetaDataResponse(struct soap*, const char*, struct tns__getFileMetaDataResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__getResponse
#define SOAP_TYPE_PointerTotns__getResponse (83)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__getResponse(struct soap*, struct tns__getResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotns__getResponse(struct soap*, struct tns__getResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotns__getResponse(struct soap*, struct tns__getResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__getResponse(struct soap*, struct tns__getResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__getResponse(struct soap*, const char *, int, struct tns__getResponse *const*, const char *);
SOAP_FMAC3 struct tns__getResponse ** SOAP_FMAC4 soap_get_PointerTotns__getResponse(struct soap*, struct tns__getResponse **, const char*, const char*);
SOAP_FMAC3 struct tns__getResponse ** SOAP_FMAC4 soap_in_PointerTotns__getResponse(struct soap*, const char*, struct tns__getResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__mkPermanentResponse
#define SOAP_TYPE_PointerTotns__mkPermanentResponse (80)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__mkPermanentResponse(struct soap*, struct tns__mkPermanentResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotns__mkPermanentResponse(struct soap*, struct tns__mkPermanentResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotns__mkPermanentResponse(struct soap*, struct tns__mkPermanentResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__mkPermanentResponse(struct soap*, struct tns__mkPermanentResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__mkPermanentResponse(struct soap*, const char *, int, struct tns__mkPermanentResponse *const*, const char *);
SOAP_FMAC3 struct tns__mkPermanentResponse ** SOAP_FMAC4 soap_get_PointerTotns__mkPermanentResponse(struct soap*, struct tns__mkPermanentResponse **, const char*, const char*);
SOAP_FMAC3 struct tns__mkPermanentResponse ** SOAP_FMAC4 soap_in_PointerTotns__mkPermanentResponse(struct soap*, const char*, struct tns__mkPermanentResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__setFileStatusResponse
#define SOAP_TYPE_PointerTotns__setFileStatusResponse (77)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__setFileStatusResponse(struct soap*, struct tns__setFileStatusResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotns__setFileStatusResponse(struct soap*, struct tns__setFileStatusResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotns__setFileStatusResponse(struct soap*, struct tns__setFileStatusResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__setFileStatusResponse(struct soap*, struct tns__setFileStatusResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__setFileStatusResponse(struct soap*, const char *, int, struct tns__setFileStatusResponse *const*, const char *);
SOAP_FMAC3 struct tns__setFileStatusResponse ** SOAP_FMAC4 soap_get_PointerTotns__setFileStatusResponse(struct soap*, struct tns__setFileStatusResponse **, const char*, const char*);
SOAP_FMAC3 struct tns__setFileStatusResponse ** SOAP_FMAC4 soap_in_PointerTotns__setFileStatusResponse(struct soap*, const char*, struct tns__setFileStatusResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__unPinResponse
#define SOAP_TYPE_PointerTotns__unPinResponse (74)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__unPinResponse(struct soap*, struct tns__unPinResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotns__unPinResponse(struct soap*, struct tns__unPinResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotns__unPinResponse(struct soap*, struct tns__unPinResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__unPinResponse(struct soap*, struct tns__unPinResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__unPinResponse(struct soap*, const char *, int, struct tns__unPinResponse *const*, const char *);
SOAP_FMAC3 struct tns__unPinResponse ** SOAP_FMAC4 soap_get_PointerTotns__unPinResponse(struct soap*, struct tns__unPinResponse **, const char*, const char*);
SOAP_FMAC3 struct tns__unPinResponse ** SOAP_FMAC4 soap_in_PointerTotns__unPinResponse(struct soap*, const char*, struct tns__unPinResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__pinResponse
#define SOAP_TYPE_PointerTotns__pinResponse (71)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__pinResponse(struct soap*, struct tns__pinResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotns__pinResponse(struct soap*, struct tns__pinResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotns__pinResponse(struct soap*, struct tns__pinResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__pinResponse(struct soap*, struct tns__pinResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__pinResponse(struct soap*, const char *, int, struct tns__pinResponse *const*, const char *);
SOAP_FMAC3 struct tns__pinResponse ** SOAP_FMAC4 soap_get_PointerTotns__pinResponse(struct soap*, struct tns__pinResponse **, const char*, const char*);
SOAP_FMAC3 struct tns__pinResponse ** SOAP_FMAC4 soap_in_PointerTotns__pinResponse(struct soap*, const char*, struct tns__pinResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__advisoryDeleteResponse
#define SOAP_TYPE_PointerTotns__advisoryDeleteResponse (68)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__advisoryDeleteResponse(struct soap*, struct tns__advisoryDeleteResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotns__advisoryDeleteResponse(struct soap*, struct tns__advisoryDeleteResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotns__advisoryDeleteResponse(struct soap*, struct tns__advisoryDeleteResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__advisoryDeleteResponse(struct soap*, struct tns__advisoryDeleteResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__advisoryDeleteResponse(struct soap*, const char *, int, struct tns__advisoryDeleteResponse *const*, const char *);
SOAP_FMAC3 struct tns__advisoryDeleteResponse ** SOAP_FMAC4 soap_get_PointerTotns__advisoryDeleteResponse(struct soap*, struct tns__advisoryDeleteResponse **, const char*, const char*);
SOAP_FMAC3 struct tns__advisoryDeleteResponse ** SOAP_FMAC4 soap_in_PointerTotns__advisoryDeleteResponse(struct soap*, const char*, struct tns__advisoryDeleteResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__getEstGetTimeResponse
#define SOAP_TYPE_PointerTotns__getEstGetTimeResponse (65)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__getEstGetTimeResponse(struct soap*, struct tns__getEstGetTimeResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotns__getEstGetTimeResponse(struct soap*, struct tns__getEstGetTimeResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotns__getEstGetTimeResponse(struct soap*, struct tns__getEstGetTimeResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__getEstGetTimeResponse(struct soap*, struct tns__getEstGetTimeResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__getEstGetTimeResponse(struct soap*, const char *, int, struct tns__getEstGetTimeResponse *const*, const char *);
SOAP_FMAC3 struct tns__getEstGetTimeResponse ** SOAP_FMAC4 soap_get_PointerTotns__getEstGetTimeResponse(struct soap*, struct tns__getEstGetTimeResponse **, const char*, const char*);
SOAP_FMAC3 struct tns__getEstGetTimeResponse ** SOAP_FMAC4 soap_in_PointerTotns__getEstGetTimeResponse(struct soap*, const char*, struct tns__getEstGetTimeResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__getProtocolsResponse
#define SOAP_TYPE_PointerTotns__getProtocolsResponse (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__getProtocolsResponse(struct soap*, struct tns__getProtocolsResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotns__getProtocolsResponse(struct soap*, struct tns__getProtocolsResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotns__getProtocolsResponse(struct soap*, struct tns__getProtocolsResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__getProtocolsResponse(struct soap*, struct tns__getProtocolsResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__getProtocolsResponse(struct soap*, const char *, int, struct tns__getProtocolsResponse *const*, const char *);
SOAP_FMAC3 struct tns__getProtocolsResponse ** SOAP_FMAC4 soap_get_PointerTotns__getProtocolsResponse(struct soap*, struct tns__getProtocolsResponse **, const char*, const char*);
SOAP_FMAC3 struct tns__getProtocolsResponse ** SOAP_FMAC4 soap_in_PointerTotns__getProtocolsResponse(struct soap*, const char*, struct tns__getProtocolsResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__copyResponse
#define SOAP_TYPE_PointerTotns__copyResponse (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__copyResponse(struct soap*, struct tns__copyResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotns__copyResponse(struct soap*, struct tns__copyResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotns__copyResponse(struct soap*, struct tns__copyResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__copyResponse(struct soap*, struct tns__copyResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__copyResponse(struct soap*, const char *, int, struct tns__copyResponse *const*, const char *);
SOAP_FMAC3 struct tns__copyResponse ** SOAP_FMAC4 soap_get_PointerTotns__copyResponse(struct soap*, struct tns__copyResponse **, const char*, const char*);
SOAP_FMAC3 struct tns__copyResponse ** SOAP_FMAC4 soap_in_PointerTotns__copyResponse(struct soap*, const char*, struct tns__copyResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__getRequestStatusResponse
#define SOAP_TYPE_PointerTotns__getRequestStatusResponse (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__getRequestStatusResponse(struct soap*, struct tns__getRequestStatusResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotns__getRequestStatusResponse(struct soap*, struct tns__getRequestStatusResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotns__getRequestStatusResponse(struct soap*, struct tns__getRequestStatusResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__getRequestStatusResponse(struct soap*, struct tns__getRequestStatusResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__getRequestStatusResponse(struct soap*, const char *, int, struct tns__getRequestStatusResponse *const*, const char *);
SOAP_FMAC3 struct tns__getRequestStatusResponse ** SOAP_FMAC4 soap_get_PointerTotns__getRequestStatusResponse(struct soap*, struct tns__getRequestStatusResponse **, const char*, const char*);
SOAP_FMAC3 struct tns__getRequestStatusResponse ** SOAP_FMAC4 soap_in_PointerTotns__getRequestStatusResponse(struct soap*, const char*, struct tns__getRequestStatusResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__putResponse
#define SOAP_TYPE_PointerTotns__putResponse (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__putResponse(struct soap*, struct tns__putResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotns__putResponse(struct soap*, struct tns__putResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotns__putResponse(struct soap*, struct tns__putResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__putResponse(struct soap*, struct tns__putResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__putResponse(struct soap*, const char *, int, struct tns__putResponse *const*, const char *);
SOAP_FMAC3 struct tns__putResponse ** SOAP_FMAC4 soap_get_PointerTotns__putResponse(struct soap*, struct tns__putResponse **, const char*, const char*);
SOAP_FMAC3 struct tns__putResponse ** SOAP_FMAC4 soap_in_PointerTotns__putResponse(struct soap*, const char*, struct tns__putResponse **, const char*);

#ifndef SOAP_TYPE_PointerTotns__getEstPutTimeResponse
#define SOAP_TYPE_PointerTotns__getEstPutTimeResponse (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__getEstPutTimeResponse(struct soap*, struct tns__getEstPutTimeResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotns__getEstPutTimeResponse(struct soap*, struct tns__getEstPutTimeResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotns__getEstPutTimeResponse(struct soap*, struct tns__getEstPutTimeResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__getEstPutTimeResponse(struct soap*, struct tns__getEstPutTimeResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__getEstPutTimeResponse(struct soap*, const char *, int, struct tns__getEstPutTimeResponse *const*, const char *);
SOAP_FMAC3 struct tns__getEstPutTimeResponse ** SOAP_FMAC4 soap_get_PointerTotns__getEstPutTimeResponse(struct soap*, struct tns__getEstPutTimeResponse **, const char*, const char*);
SOAP_FMAC3 struct tns__getEstPutTimeResponse ** SOAP_FMAC4 soap_in_PointerTotns__getEstPutTimeResponse(struct soap*, const char*, struct tns__getEstPutTimeResponse **, const char*);

#ifndef SOAP_TYPE_PointerToArrayOfboolean
#define SOAP_TYPE_PointerToArrayOfboolean (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToArrayOfboolean(struct soap*, struct ArrayOfboolean *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToArrayOfboolean(struct soap*, struct ArrayOfboolean *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToArrayOfboolean(struct soap*, struct ArrayOfboolean **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToArrayOfboolean(struct soap*, struct ArrayOfboolean **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToArrayOfboolean(struct soap*, const char *, int, struct ArrayOfboolean *const*, const char *);
SOAP_FMAC3 struct ArrayOfboolean ** SOAP_FMAC4 soap_get_PointerToArrayOfboolean(struct soap*, struct ArrayOfboolean **, const char*, const char*);
SOAP_FMAC3 struct ArrayOfboolean ** SOAP_FMAC4 soap_in_PointerToArrayOfboolean(struct soap*, const char*, struct ArrayOfboolean **, const char*);

#ifndef SOAP_TYPE_PointerToArrayOflong
#define SOAP_TYPE_PointerToArrayOflong (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToArrayOflong(struct soap*, struct ArrayOflong *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToArrayOflong(struct soap*, struct ArrayOflong *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToArrayOflong(struct soap*, struct ArrayOflong **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToArrayOflong(struct soap*, struct ArrayOflong **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToArrayOflong(struct soap*, const char *, int, struct ArrayOflong *const*, const char *);
SOAP_FMAC3 struct ArrayOflong ** SOAP_FMAC4 soap_get_PointerToArrayOflong(struct soap*, struct ArrayOflong **, const char*, const char*);
SOAP_FMAC3 struct ArrayOflong ** SOAP_FMAC4 soap_in_PointerToArrayOflong(struct soap*, const char*, struct ArrayOflong **, const char*);

#ifndef SOAP_TYPE_PointerTotns__pingResponse
#define SOAP_TYPE_PointerTotns__pingResponse (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__pingResponse(struct soap*, struct tns__pingResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTotns__pingResponse(struct soap*, struct tns__pingResponse *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTotns__pingResponse(struct soap*, struct tns__pingResponse **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__pingResponse(struct soap*, struct tns__pingResponse **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__pingResponse(struct soap*, const char *, int, struct tns__pingResponse *const*, const char *);
SOAP_FMAC3 struct tns__pingResponse ** SOAP_FMAC4 soap_get_PointerTotns__pingResponse(struct soap*, struct tns__pingResponse **, const char*, const char*);
SOAP_FMAC3 struct tns__pingResponse ** SOAP_FMAC4 soap_in_PointerTotns__pingResponse(struct soap*, const char*, struct tns__pingResponse **, const char*);

#ifndef SOAP_TYPE_PointerToxsd__boolean
#define SOAP_TYPE_PointerToxsd__boolean (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__boolean(struct soap*, enum _Enum1 *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToxsd__boolean(struct soap*, enum _Enum1 *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToxsd__boolean(struct soap*, enum _Enum1 **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__boolean(struct soap*, enum _Enum1 **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__boolean(struct soap*, const char *, int, enum _Enum1 *const*, const char *);
SOAP_FMAC3 enum _Enum1 ** SOAP_FMAC4 soap_get_PointerToxsd__boolean(struct soap*, enum _Enum1 **, const char*, const char*);
SOAP_FMAC3 enum _Enum1 ** SOAP_FMAC4 soap_in_PointerToxsd__boolean(struct soap*, const char*, enum _Enum1 **, const char*);

#ifndef SOAP_TYPE_PointerToArrayOfstring
#define SOAP_TYPE_PointerToArrayOfstring (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToArrayOfstring(struct soap*, struct ArrayOfstring *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToArrayOfstring(struct soap*, struct ArrayOfstring *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToArrayOfstring(struct soap*, struct ArrayOfstring **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToArrayOfstring(struct soap*, struct ArrayOfstring **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToArrayOfstring(struct soap*, const char *, int, struct ArrayOfstring *const*, const char *);
SOAP_FMAC3 struct ArrayOfstring ** SOAP_FMAC4 soap_get_PointerToArrayOfstring(struct soap*, struct ArrayOfstring **, const char*, const char*);
SOAP_FMAC3 struct ArrayOfstring ** SOAP_FMAC4 soap_in_PointerToArrayOfstring(struct soap*, const char*, struct ArrayOfstring **, const char*);

#ifndef SOAP_TYPE_PointerToArrayOfFileMetaData
#define SOAP_TYPE_PointerToArrayOfFileMetaData (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToArrayOfFileMetaData(struct soap*, struct ArrayOfFileMetaData *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToArrayOfFileMetaData(struct soap*, struct ArrayOfFileMetaData *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToArrayOfFileMetaData(struct soap*, struct ArrayOfFileMetaData **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToArrayOfFileMetaData(struct soap*, struct ArrayOfFileMetaData **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToArrayOfFileMetaData(struct soap*, const char *, int, struct ArrayOfFileMetaData *const*, const char *);
SOAP_FMAC3 struct ArrayOfFileMetaData ** SOAP_FMAC4 soap_get_PointerToArrayOfFileMetaData(struct soap*, struct ArrayOfFileMetaData **, const char*, const char*);
SOAP_FMAC3 struct ArrayOfFileMetaData ** SOAP_FMAC4 soap_in_PointerToArrayOfFileMetaData(struct soap*, const char*, struct ArrayOfFileMetaData **, const char*);

#ifndef SOAP_TYPE_PointerTons11__RequestFileStatus
#define SOAP_TYPE_PointerTons11__RequestFileStatus (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons11__RequestFileStatus(struct soap*, struct ns11__RequestFileStatus *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTons11__RequestFileStatus(struct soap*, struct ns11__RequestFileStatus *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTons11__RequestFileStatus(struct soap*, struct ns11__RequestFileStatus **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons11__RequestFileStatus(struct soap*, struct ns11__RequestFileStatus **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons11__RequestFileStatus(struct soap*, const char *, int, struct ns11__RequestFileStatus *const*, const char *);
SOAP_FMAC3 struct ns11__RequestFileStatus ** SOAP_FMAC4 soap_get_PointerTons11__RequestFileStatus(struct soap*, struct ns11__RequestFileStatus **, const char*, const char*);
SOAP_FMAC3 struct ns11__RequestFileStatus ** SOAP_FMAC4 soap_in_PointerTons11__RequestFileStatus(struct soap*, const char*, struct ns11__RequestFileStatus **, const char*);

#ifndef SOAP_TYPE_PointerToxsd__long
#define SOAP_TYPE_PointerToxsd__long (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__long(struct soap*, LONG64 *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToxsd__long(struct soap*, LONG64 *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToxsd__long(struct soap*, LONG64 **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__long(struct soap*, LONG64 **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__long(struct soap*, const char *, int, LONG64 *const*, const char *);
SOAP_FMAC3 LONG64 ** SOAP_FMAC4 soap_get_PointerToxsd__long(struct soap*, LONG64 **, const char*, const char*);
SOAP_FMAC3 LONG64 ** SOAP_FMAC4 soap_in_PointerToxsd__long(struct soap*, const char*, LONG64 **, const char*);

#ifndef SOAP_TYPE_PointerToxsd__string
#define SOAP_TYPE_PointerToxsd__string (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__string(struct soap*, char **const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToxsd__string(struct soap*, char **const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToxsd__string(struct soap*, char ***);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__string(struct soap*, char ***, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__string(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerToxsd__string(struct soap*, char ***, const char*, const char*);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerToxsd__string(struct soap*, const char*, char ***, const char*);

#ifndef SOAP_TYPE_PointerTons11__FileMetaData
#define SOAP_TYPE_PointerTons11__FileMetaData (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons11__FileMetaData(struct soap*, struct ns11__FileMetaData *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTons11__FileMetaData(struct soap*, struct ns11__FileMetaData *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTons11__FileMetaData(struct soap*, struct ns11__FileMetaData **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons11__FileMetaData(struct soap*, struct ns11__FileMetaData **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons11__FileMetaData(struct soap*, const char *, int, struct ns11__FileMetaData *const*, const char *);
SOAP_FMAC3 struct ns11__FileMetaData ** SOAP_FMAC4 soap_get_PointerTons11__FileMetaData(struct soap*, struct ns11__FileMetaData **, const char*, const char*);
SOAP_FMAC3 struct ns11__FileMetaData ** SOAP_FMAC4 soap_in_PointerTons11__FileMetaData(struct soap*, const char*, struct ns11__FileMetaData **, const char*);

#ifndef SOAP_TYPE_PointerToArrayOfRequestFileStatus
#define SOAP_TYPE_PointerToArrayOfRequestFileStatus (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToArrayOfRequestFileStatus(struct soap*, struct ArrayOfRequestFileStatus *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerToArrayOfRequestFileStatus(struct soap*, struct ArrayOfRequestFileStatus *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerToArrayOfRequestFileStatus(struct soap*, struct ArrayOfRequestFileStatus **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToArrayOfRequestFileStatus(struct soap*, struct ArrayOfRequestFileStatus **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToArrayOfRequestFileStatus(struct soap*, const char *, int, struct ArrayOfRequestFileStatus *const*, const char *);
SOAP_FMAC3 struct ArrayOfRequestFileStatus ** SOAP_FMAC4 soap_get_PointerToArrayOfRequestFileStatus(struct soap*, struct ArrayOfRequestFileStatus **, const char*, const char*);
SOAP_FMAC3 struct ArrayOfRequestFileStatus ** SOAP_FMAC4 soap_in_PointerToArrayOfRequestFileStatus(struct soap*, const char*, struct ArrayOfRequestFileStatus **, const char*);

#ifndef SOAP_TYPE_PointerTons11__RequestStatus
#define SOAP_TYPE_PointerTons11__RequestStatus (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons11__RequestStatus(struct soap*, struct ns11__RequestStatus *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_PointerTons11__RequestStatus(struct soap*, struct ns11__RequestStatus *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_PointerTons11__RequestStatus(struct soap*, struct ns11__RequestStatus **);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons11__RequestStatus(struct soap*, struct ns11__RequestStatus **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons11__RequestStatus(struct soap*, const char *, int, struct ns11__RequestStatus *const*, const char *);
SOAP_FMAC3 struct ns11__RequestStatus ** SOAP_FMAC4 soap_get_PointerTons11__RequestStatus(struct soap*, struct ns11__RequestStatus **, const char*, const char*);
SOAP_FMAC3 struct ns11__RequestStatus ** SOAP_FMAC4 soap_in_PointerTons11__RequestStatus(struct soap*, const char*, struct ns11__RequestStatus **, const char*);

#ifndef SOAP_TYPE_xsd__dateTime
#define SOAP_TYPE_xsd__dateTime (6)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__dateTime(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__dateTime(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__dateTime(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__dateTime(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__dateTime(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__dateTime(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__dateTime(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__string(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_xsd__string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__string(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_mark_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

SOAP_END_NAMESPACE(srm)

#ifdef __cplusplus
}
#endif

#endif

/* end of srmH.h */
