/* srmsoapSRMServerV1Proxy.h
   Generated by gSOAP 2.3.8 from srm.v1.1.h
   Copyright (C) 2001-2003 Genivia inc.
   All Rights Reserved.
*/

#ifndef srmsoapSRMServerV1_H
#define srmsoapSRMServerV1_H
#include "srmH.h"
SOAP_BEGIN_NAMESPACE(srm)
class soapSRMServerV1
{   public:
	struct soap *soap;
	const char *endpoint;
	soapSRMServerV1() { soap = soap_new(); endpoint = "http://wacdr002d.cern.ch:8082/srm/managerv1"; };
	virtual ~soapSRMServerV1() { if (soap) { soap_destroy(soap); soap_end(soap); soap_done(soap); SOAP_FREE((void*)soap); } };
	virtual int ping(struct tns__pingResponse *out) { return soap ? soap_call_tns__ping(soap, endpoint, NULL, out) : SOAP_EOM; };
	virtual int getEstPutTime(struct ArrayOfstring *arg0, struct ArrayOfstring *arg1, struct ArrayOflong *arg2, struct ArrayOfboolean *arg3, struct ArrayOfstring *arg4, struct tns__getEstPutTimeResponse *out) { return soap ? soap_call_tns__getEstPutTime(soap, endpoint, NULL, arg0, arg1, arg2, arg3, arg4, out) : SOAP_EOM; };
	virtual int put(struct ArrayOfstring *arg0, struct ArrayOfstring *arg1, struct ArrayOflong *arg2, struct ArrayOfboolean *arg3, struct ArrayOfstring *arg4, struct tns__putResponse *out) { return soap ? soap_call_tns__put(soap, endpoint, NULL, arg0, arg1, arg2, arg3, arg4, out) : SOAP_EOM; };
	virtual int getRequestStatus(int arg0, struct tns__getRequestStatusResponse *out) { return soap ? soap_call_tns__getRequestStatus(soap, endpoint, NULL, arg0, out) : SOAP_EOM; };
	virtual int copy(struct ArrayOfstring *arg0, struct ArrayOfstring *arg1, struct ArrayOfboolean *arg2, struct tns__copyResponse *out) { return soap ? soap_call_tns__copy(soap, endpoint, NULL, arg0, arg1, arg2, out) : SOAP_EOM; };
	virtual int getProtocols(struct tns__getProtocolsResponse *out) { return soap ? soap_call_tns__getProtocols(soap, endpoint, NULL, out) : SOAP_EOM; };
	virtual int getEstGetTime(struct ArrayOfstring *arg0, struct ArrayOfstring *arg1, struct tns__getEstGetTimeResponse *out) { return soap ? soap_call_tns__getEstGetTime(soap, endpoint, NULL, arg0, arg1, out) : SOAP_EOM; };
	virtual int advisoryDelete(struct ArrayOfstring *arg0, struct tns__advisoryDeleteResponse *out) { return soap ? soap_call_tns__advisoryDelete(soap, endpoint, NULL, arg0, out) : SOAP_EOM; };
	virtual int pin(struct ArrayOfstring *arg0, struct tns__pinResponse *out) { return soap ? soap_call_tns__pin(soap, endpoint, NULL, arg0, out) : SOAP_EOM; };
	virtual int unPin(struct ArrayOfstring *arg0, int arg1, struct tns__unPinResponse *out) { return soap ? soap_call_tns__unPin(soap, endpoint, NULL, arg0, arg1, out) : SOAP_EOM; };
	virtual int setFileStatus(int arg0, int arg1, char *arg2, struct tns__setFileStatusResponse *out) { return soap ? soap_call_tns__setFileStatus(soap, endpoint, NULL, arg0, arg1, arg2, out) : SOAP_EOM; };
	virtual int mkPermanent(struct ArrayOfstring *arg0, struct tns__mkPermanentResponse *out) { return soap ? soap_call_tns__mkPermanent(soap, endpoint, NULL, arg0, out) : SOAP_EOM; };
	virtual int get(struct ArrayOfstring *arg0, struct ArrayOfstring *arg1, struct tns__getResponse *out) { return soap ? soap_call_tns__get(soap, endpoint, NULL, arg0, arg1, out) : SOAP_EOM; };
	virtual int getFileMetaData(struct ArrayOfstring *arg0, struct tns__getFileMetaDataResponse *out) { return soap ? soap_call_tns__getFileMetaData(soap, endpoint, NULL, arg0, out) : SOAP_EOM; };
};
SOAP_END_NAMESPACE(srm)
#endif
