/* srmServerLib.c
   Generated by gSOAP 2.3.8 from srm.v1.1.h
   Copyright (C) 2001-2003 Genivia inc.
   All Rights Reserved.
*/
#define WITH_NOGLOBAL
#define SOAP_FMAC3 static
#include "srmC.c"
#include "srmServer.c"

/* end of srmServerLib.c */
