/* srmStub.h
   Generated by gSOAP 2.3.8 from srm.v1.1.h
   Copyright (C) 2001-2003 Genivia inc.
   All Rights Reserved.
*/
#ifndef srmStub_H
#define srmStub_H
#include "stdsoap2.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_BEGIN_NAMESPACE(srm)

/* Enumerations */

#ifndef _SOAP__Enum1
#define _SOAP__Enum1
enum _Enum1 {false_ = 0, true_ = 1};
#endif

/* Classes and Structs */

/* tns:getResponse: */
struct tns__getResponse
{
	struct ns11__RequestStatus *_Result;	/* return */
};

/* tns:advisoryDeleteResponse: */
struct tns__advisoryDeleteResponse
{
};

/* ns11:RequestStatus: */
struct ns11__RequestStatus
{
	int requestId;
	char *type;
	char *state;
	char *submitTime;
	char *startTime;
	char *finishTime;
	int estTimeToStart;
	struct ArrayOfRequestFileStatus *fileStatuses;
	char *errorMessage;
	int retryDeltaTime;
};

/* Array of ns11:FileMetaData schema type: */
struct ArrayOfFileMetaData
{
	struct ns11__FileMetaData *__ptr;
	int __size;
	int __offset;
};

/* Array of xsd:string schema type: */
struct ArrayOfstring
{
	char **__ptr;
	int __size;
	int __offset;
};

/* Array of xsd:long schema type: */
struct ArrayOflong
{
	LONG64 *__ptr;
	int __size;
	int __offset;
};

/* tns:putResponse: */
struct tns__putResponse
{
	struct ns11__RequestStatus *_Result;	/* return */
};

/* Array of ns11:RequestFileStatus schema type: */
struct ArrayOfRequestFileStatus
{
	struct ns11__RequestFileStatus *__ptr;
	int __size;
	int __offset;
};

/* tns:mkPermanentResponse: */
struct tns__mkPermanentResponse
{
	struct ns11__RequestStatus *_Result;	/* return */
};

/* tns:copyResponse: */
struct tns__copyResponse
{
	struct ns11__RequestStatus *_Result;	/* return */
};

/* tns:getEstGetTimeResponse: */
struct tns__getEstGetTimeResponse
{
	struct ns11__RequestStatus *_Result;	/* return */
};

/* tns:getEstPutTimeResponse: */
struct tns__getEstPutTimeResponse
{
	struct ns11__RequestStatus *_Result;	/* return */
};

/* tns:pinResponse: */
struct tns__pinResponse
{
	struct ns11__RequestStatus *_Result;	/* return */
};

/* tns:pingResponse: */
struct tns__pingResponse
{
	enum _Enum1 _Result;	/* return */
};

/* tns:getFileMetaDataResponse: */
struct tns__getFileMetaDataResponse
{
	struct ArrayOfFileMetaData *_Result;	/* return */
};

/* tns:getRequestStatusResponse: */
struct tns__getRequestStatusResponse
{
	struct ns11__RequestStatus *_Result;	/* return */
};

/* tns:getProtocolsResponse: */
struct tns__getProtocolsResponse
{
	struct ArrayOfstring *_Result;	/* return */
};

/* tns:setFileStatusResponse: */
struct tns__setFileStatusResponse
{
	struct ns11__RequestStatus *_Result;	/* return */
};

/* ns11:FileMetaData: */
struct ns11__FileMetaData
{
	char *SURL;
	LONG64 size;
	char *owner;
	char *group;
	int permMode;
	char *checksumType;
	char *checksumValue;
	enum _Enum1 isPinned;
	enum _Enum1 isPermanent;
	enum _Enum1 isCached;
};

/* tns:unPinResponse: */
struct tns__unPinResponse
{
	struct ns11__RequestStatus *_Result;	/* return */
};

/* Array of xsd:boolean schema type: */
struct ArrayOfboolean
{
	enum _Enum1 *__ptr;
	int __size;
	int __offset;
};

/* ns11:RequestFileStatus: */
struct ns11__RequestFileStatus
{
	char *SURL;
	LONG64 size;
	char *owner;
	char *group;
	int permMode;
	char *checksumType;
	char *checksumValue;
	enum _Enum1 isPinned;
	enum _Enum1 isPermanent;
	enum _Enum1 isCached;
	char *state;
	int fileId;
	char *TURL;
	int estSecondsToStart;
	char *sourceFilename;
	char *destFilename;
	int queueOrder;
};

/* tns:ping: */
struct tns__ping
{
};

/* tns:getEstPutTime: */
struct tns__getEstPutTime
{
	struct ArrayOfstring *arg0;
	struct ArrayOfstring *arg1;
	struct ArrayOflong *arg2;
	struct ArrayOfboolean *arg3;
	struct ArrayOfstring *arg4;
};

/* tns:put: */
struct tns__put
{
	struct ArrayOfstring *arg0;
	struct ArrayOfstring *arg1;
	struct ArrayOflong *arg2;
	struct ArrayOfboolean *arg3;
	struct ArrayOfstring *arg4;
};

/* tns:getRequestStatus: */
struct tns__getRequestStatus
{
	int arg0;
};

/* tns:copy: */
struct tns__copy
{
	struct ArrayOfstring *arg0;
	struct ArrayOfstring *arg1;
	struct ArrayOfboolean *arg2;
};

/* tns:getProtocols: */
struct tns__getProtocols
{
};

/* tns:getEstGetTime: */
struct tns__getEstGetTime
{
	struct ArrayOfstring *arg0;
	struct ArrayOfstring *arg1;
};

/* tns:advisoryDelete: */
struct tns__advisoryDelete
{
	struct ArrayOfstring *arg0;
};

/* tns:pin: */
struct tns__pin
{
	struct ArrayOfstring *arg0;
};

/* tns:unPin: */
struct tns__unPin
{
	struct ArrayOfstring *arg0;
	int arg1;
};

/* tns:setFileStatus: */
struct tns__setFileStatus
{
	int arg0;
	int arg1;
	char *arg2;
};

/* tns:mkPermanent: */
struct tns__mkPermanent
{
	struct ArrayOfstring *arg0;
};

/* tns:get: */
struct tns__get
{
	struct ArrayOfstring *arg0;
	struct ArrayOfstring *arg1;
};

/* tns:getFileMetaData: */
struct tns__getFileMetaData
{
	struct ArrayOfstring *arg0;
};

/* SOAP Header: */
struct SOAP_ENV__Header
{
	void *dummy;	/* transient */
};

/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;
	char *SOAP_ENV__Node;
	char *SOAP_ENV__Role;
};

/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;
	char *faultstring;
	char *faultactor;
	char *detail;
	struct SOAP_ENV__Code *SOAP_ENV__Code;
	char *SOAP_ENV__Reason;
	char *SOAP_ENV__Detail;
};

/* Types With Custom (De)serializers: */

/* Typedefs */
typedef char *xsd__string;
typedef int xsd__int;
typedef char *xsd__dateTime;
typedef LONG64 xsd__long;
typedef enum _Enum1 xsd__boolean;
typedef enum _Enum1 tns__Boolean;
typedef LONG64 tns__Long;
typedef int tns__Integer;
typedef char *_QName;

/* Extern */

/* Remote Methods */

SOAP_FMAC5 int SOAP_FMAC6 tns__ping(struct soap*, struct tns__pingResponse *);

SOAP_FMAC5 int SOAP_FMAC6 tns__getEstPutTime(struct soap*, struct ArrayOfstring *, struct ArrayOfstring *, struct ArrayOflong *, struct ArrayOfboolean *, struct ArrayOfstring *, struct tns__getEstPutTimeResponse *);

SOAP_FMAC5 int SOAP_FMAC6 tns__put(struct soap*, struct ArrayOfstring *, struct ArrayOfstring *, struct ArrayOflong *, struct ArrayOfboolean *, struct ArrayOfstring *, struct tns__putResponse *);

SOAP_FMAC5 int SOAP_FMAC6 tns__getRequestStatus(struct soap*, int, struct tns__getRequestStatusResponse *);

SOAP_FMAC5 int SOAP_FMAC6 tns__copy(struct soap*, struct ArrayOfstring *, struct ArrayOfstring *, struct ArrayOfboolean *, struct tns__copyResponse *);

SOAP_FMAC5 int SOAP_FMAC6 tns__getProtocols(struct soap*, struct tns__getProtocolsResponse *);

SOAP_FMAC5 int SOAP_FMAC6 tns__getEstGetTime(struct soap*, struct ArrayOfstring *, struct ArrayOfstring *, struct tns__getEstGetTimeResponse *);

SOAP_FMAC5 int SOAP_FMAC6 tns__advisoryDelete(struct soap*, struct ArrayOfstring *, struct tns__advisoryDeleteResponse *);

SOAP_FMAC5 int SOAP_FMAC6 tns__pin(struct soap*, struct ArrayOfstring *, struct tns__pinResponse *);

SOAP_FMAC5 int SOAP_FMAC6 tns__unPin(struct soap*, struct ArrayOfstring *, int, struct tns__unPinResponse *);

SOAP_FMAC5 int SOAP_FMAC6 tns__setFileStatus(struct soap*, int, int, char *, struct tns__setFileStatusResponse *);

SOAP_FMAC5 int SOAP_FMAC6 tns__mkPermanent(struct soap*, struct ArrayOfstring *, struct tns__mkPermanentResponse *);

SOAP_FMAC5 int SOAP_FMAC6 tns__get(struct soap*, struct ArrayOfstring *, struct ArrayOfstring *, struct tns__getResponse *);

SOAP_FMAC5 int SOAP_FMAC6 tns__getFileMetaData(struct soap*, struct ArrayOfstring *, struct tns__getFileMetaDataResponse *);

/* Stubs */

SOAP_FMAC5 int SOAP_FMAC6 soap_call_tns__ping(struct soap*, const char*, const char*, struct tns__pingResponse *);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_tns__getEstPutTime(struct soap*, const char*, const char*, struct ArrayOfstring *, struct ArrayOfstring *, struct ArrayOflong *, struct ArrayOfboolean *, struct ArrayOfstring *, struct tns__getEstPutTimeResponse *);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_tns__put(struct soap*, const char*, const char*, struct ArrayOfstring *, struct ArrayOfstring *, struct ArrayOflong *, struct ArrayOfboolean *, struct ArrayOfstring *, struct tns__putResponse *);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_tns__getRequestStatus(struct soap*, const char*, const char*, int, struct tns__getRequestStatusResponse *);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_tns__copy(struct soap*, const char*, const char*, struct ArrayOfstring *, struct ArrayOfstring *, struct ArrayOfboolean *, struct tns__copyResponse *);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_tns__getProtocols(struct soap*, const char*, const char*, struct tns__getProtocolsResponse *);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_tns__getEstGetTime(struct soap*, const char*, const char*, struct ArrayOfstring *, struct ArrayOfstring *, struct tns__getEstGetTimeResponse *);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_tns__advisoryDelete(struct soap*, const char*, const char*, struct ArrayOfstring *, struct tns__advisoryDeleteResponse *);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_tns__pin(struct soap*, const char*, const char*, struct ArrayOfstring *, struct tns__pinResponse *);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_tns__unPin(struct soap*, const char*, const char*, struct ArrayOfstring *, int, struct tns__unPinResponse *);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_tns__setFileStatus(struct soap*, const char*, const char*, int, int, char *, struct tns__setFileStatusResponse *);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_tns__mkPermanent(struct soap*, const char*, const char*, struct ArrayOfstring *, struct tns__mkPermanentResponse *);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_tns__get(struct soap*, const char*, const char*, struct ArrayOfstring *, struct ArrayOfstring *, struct tns__getResponse *);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_tns__getFileMetaData(struct soap*, const char*, const char*, struct ArrayOfstring *, struct tns__getFileMetaDataResponse *);

/* Skeletons */

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_tns__ping(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_tns__getEstPutTime(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_tns__put(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_tns__getRequestStatus(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_tns__copy(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_tns__getProtocols(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_tns__getEstGetTime(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_tns__advisoryDelete(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_tns__pin(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_tns__unPin(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_tns__setFileStatus(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_tns__mkPermanent(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_tns__get(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_tns__getFileMetaData(struct soap*);

SOAP_END_NAMESPACE(srm)

#ifdef __cplusplus
}
#endif

#endif

/* end of srmStub.h */
