/* srmsoapSRMServerV1Object.h
   Generated by gSOAP 2.3.8 from srm.v1.1.h
   Copyright (C) 2001-2003 Genivia inc.
   All Rights Reserved.
*/

#ifndef srmsoapSRMServerV1_H
#define srmsoapSRMServerV1_H
#include "srmH.h"
SOAP_BEGIN_NAMESPACE(srm)
class soapSRMServerV1 : public soap
{    public:
	soapSRMServerV1() { soap_init(this); };
	~soapSRMServerV1() { soap_destroy(this); soap_end(this); soap_done(this); };
	int serve() { return soap_serve(this); };
};
SOAP_END_NAMESPACE(srm)
#endif
